version: '3.9'

services:
  app_server:
    container_name: app_server
    image: app_server:2.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    env_file: .env
    ports:
      - '127.0.0.1:3000:3000'
      - '127.0.0.1:9229:9229'
    volumes:
      - .:/usr/src/app:ro
      - /usr/src/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
